### ISSUE TITLE
sdp_extract_data, locations = multiple polygons

### ISSUE THREAD

**Issue by AmandaNHenderson** [rmbl-sdp/rSDP#2]
```
## bring in landcover raster
lc <- sdp_get_raster(catalog_id="R3D018") 
## bring in 8 polygons as sf
field_planning = st_read("C:/Users/AmandaHenderson/SynologyDrive/UER_vegmap/output/sampling_areas_draft.gpkg")
## extract landcover data for polygons of interest
fp_lc = sdp_extract_data(raster = lc, locations = field_planning)
#[1] "Re-projecting locations to coordinate system of the raster."
#[1] "Extracting data at 8 locations for 1 raster layers."
#Error: [cbind] nrow does not match
```

Notes:
Same error when locations is SpatVector
sdp_extract_data(raster = lc, locations = field_planning, bind = FALSE) works, but returns a dataframe, which is less useful

**Comment by ikb-rmbl** [comment]
This was happening with line or polygon inputs, related to the default behavior of `terra::extract()` , returning all cell values that intersect input features unless a summary function (e.g. mean, median etc.) is specified.

The default behavior with polygons and lines now summarizes  by polygon, computing means by default. I've added another option `sum_fun` to allow specifying other summary functions.
