### ISSUE TITLE
README errors

### ISSUE THREAD

**Issue by wpetry** [rmbl-sdp/rSDP#3]
I ran the code in the README and caught a few reproducibility errors. They are all minor, so collecting here under a single issue.
1. Plotting with map tiles doesn't work
https://github.com/rmbl-sdp/rSDP/blob/d16a32b80f565de22c1e26f757dcca7b3cf565e7/README.Rmd#L70
`Error in leaflet::addRasterImage(map, x, colors = col, opacity = alpha,  : 
  inherits(x, "RasterLayer") is not TRUE`

Are raster data types supported when using tiles? Maybe this is a simple fix with class conversion?
2. Download argument misnamed
https://github.com/rmbl-sdp/rSDP/blob/d16a32b80f565de22c1e26f757dcca7b3cf565e7/README.Rmd#L78-L81
`download_data` should be changed to `download_files`
3. Timing extraction approaches
https://github.com/rmbl-sdp/rSDP/blob/d16a32b80f565de22c1e26f757dcca7b3cf565e7/README.md#L297-L301
Looks like something slowed down the foreach run. I get ~2x speedup.

**Comment by ikb-rmbl** [comment]
Great! README reproducibility issues should be resolved in the latest update.
